version: '3.4'

services:
  sampleapi:
    image: sampleapi:dev
    container_name: SampleAPI
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "SampleAPI"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_sampleapi$
    volumes:
      - /Users/selmanhanci/Projects/SampleMinimalAPI/SampleAPI:/app
      - /Users/selmanhanci/Projects/SampleMinimalAPI:/src
      - /Users/selmanhanci/vsdbg/vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_sampleapi$

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_sampleapi$ \"/app/bin/Debug/net6.0/SampleAPI.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true